var mongoose = require('mongoose');
var mongooseAutoIncrement = require('mongoose-auto-increment');

// Flow defines a yoga routine to be generated by our algorithm
var flowSchema = mongoose.Schema({

    created_at        : { type: Date, default: Date.now },
    updated_at        : { type: Date, default: Date.now },
    name              : String,
    description       : String,
    duration_ms       : Number,
    
    //A flow_segment defines a set of constraints for a block of time
    flow_segments     : [{
        name          : String,
        // specify target amount of time to spend in this segment
        duration_ms   : Number,
        // specify any video that must be in this segment
        video_ids     : [{
            type      : Number,
            ref       : 'Video'
        }],
        // specify any tag that videos in this segment must have
        tags          : [ String ]
    }],

    user_id           : {
        type          : Number,
        ref           : 'User'
    },
    tags              : [ String ]
}, { strict: 'throw'});

flowSchema.plugin(mongooseAutoIncrement.plugin, 'Flow');
module.exports = mongoose.model('Flow', flowSchema);
